apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-universe
  labels:
    app: hello-universe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-universe
  template:
    metadata:
      labels:
        app: hello-universe
    spec:
      containers:
      - name: hello-universe
        image: mpetason/hello-universe
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-universe
spec:
  ports:
  - port: 8080
  selector:
    app: hello-universe
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "cert-manager"
spec:
  tls:
  - hosts:
    - kohei-kevin.com
    secretName: demo-key
  rules:
  - host: "kohei-kevin.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hello-world
            port:
              number: 8080
      - pathType: Prefix
        path: /hello-universe
        backend:
          service:
            name: hello-universe
            port:
              number: 8080