apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example2
  namespace: example
  labels: 
    app: nginx-example2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-example2
  template:
    metadata:
      labels:
        app: nginx-example2
    spec:
      containers:
      - name: nginx-example2
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-example2
  namespace: example
spec:
  type: ClusterIP
  selector:
    app: nginx-example2
  ports:
  - port: 80
---
apiVersion: networking.k8s.io/v1
# apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-example2
  namespace: example
  annotations:
    # kubernetes.io/ingress.class: "nginx"
    # cert-manager.io/cluster-issuer: "letsencrypt-staging"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # cert-manager.io/cluster-issuer: "cert-manager"
spec:
  tls:
  - hosts:
    - banana2.kohei-kevin.com
    secretName: demo-key
  rules:
  - host: "banana2.kohei-kevin.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-example2
            port:
              number: 80

