apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: nginx:latest
          ports:
            - containerPort: 80
 
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: example
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
  - port: 80
 
---
apiVersion: networking.k8s.io/v1
# apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: example
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # cert-manager.io/cluster-issuer: "cert-manager"
    # cert-manager.io/cluster-issuer: "letsencrypt-staging"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - kohei-kevin.com
      # secretName: my-ingress
  rules:
  - host: kohei-kevin.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-service
            port:
              number: 80

